[package]
name = "raytracer"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = "0.9"
image = {version = "0.25.9", features = ["rayon"]}
rayon = "1.11.0"
indicatif = {version = "0.18.3", features = ["rayon"]}

[profile.release]
debug = 1